# - name: download and install xray
#   shell: 'bash -c "$(curl -L https://raw.githubusercontent.com/XTLS/Xray-install/046d9aa2432b3a6241d73c3684ef4e512974b594/install-release.sh)" @ install --version 1.8.1;'

- name: Copy config file
  template: src=xray_config dest=/usr/local/etc/xray/config.json

- name: Restart xray service
  service: name=xray state=restarted